version: "3.9"
services:
  mongo:
    image: mongo:5.0.9
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - TZ=Asia/Shanghai
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    depends_on:
      - "mongo"
